<!-- https://www.osano.com/ -->
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#062156"
    },
    "button": {
      "background": "transparent",
      "border": "#ffffff",
      "text": "#ffffff"
    }
  },
  "position": "bottom-right",
  "content": {
    "message": "Wir nutzen Cookies auf dieser Seite, um die Benutzerfreundlichkeit zu verbessern",
    "dismiss": "Akzeptieren ",
    "link": "Datenschutzerklärung ",
    "href": "<?php echo $url ?>/Datenschutz/"
  }
});
</script>