    <div id="upButton" class="">
        <i class="fas fa-chevron-up"></i>
    </div>
    <footer>
        <div>
            <div class="ivdImg"></div>
            <ul>
                <li><a href="<?php echo $url ?>/Unternehmen/">Unternehmen</a></li>
                <li><a href="<?php echo $url ?>/Leistungen/">Leistungen</a></li>
                <li><a href="<?php echo $url ?>/Kontakt/">Kontakt</a></li>
                <li><a href="<?php echo $url ?>/Datenschutz/">Datenschutz</a></li>
                <li><a href="<?php echo $url ?>/Widerrufsrecht/">Widerrufsrecht</a></li>
                <li><a href="<?php echo $url ?>/Impressum/">Impressum</a></li>
            </ul>
        </div>
        <p>© HONNEF Immobilien <?php echo date("Y"); ?></p>
    </footer>
    <?php require_once('cookie.phtml'); ?>
</body>
</html>