<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="description" content="Wir bieten Ihnen eine breite Palette an Immobilienservice mit Pfiff und Herz in Gotha.">
    <meta name="keywords" content="Gotha, Immobilien, HONNEF Immobilien, HONNEF, Honnef, Hausverwaltung, Immobilienbuero, Verkaufen, Vermieten, Verwalten, Vertrauen, Objekte, Wohnungen">
    <meta name="author" content="Linus-Alexander Steinert, Steffen Bollwahn">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://kit.fontawesome.com/57e9b76792.js"></script>
    <script src='https://www.google.com/recaptcha/api.js' async defer></script>

    <link rel="icon" href="../img/großesHMiniIcon.jpg" type="image/x-icon">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
    <script type="module" src="./js/main.js"></script>